name: Deploy (no-npm)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}  # ou key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd "${{ secrets.VPS_PATH }}"
            # remets les droits proprement (évite les 'Permission denied')
            sudo chown -R $USER:$USER .
            git fetch --all --tags
            git reset --hard origin/main || git reset --hard origin/master
            sudo systemctl reload nginx 2>/dev/null || true
            sudo systemctl reload apache2 2>/dev/null || true
            echo "✅ Déploiement terminé (sans npm)"
