name: Deploy (password)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script_stop: true
          script: |
            set -e
            cd "${{ secrets.VPS_PATH }}"
            git fetch --all --tags
            git reset --hard origin/main || git reset --hard origin/master
            if [ -f package.json ]; then
              npm ci || npm install
              npm run build || true
            fi
            sudo systemctl reload nginx 2>/dev/null || true
            sudo systemctl reload apache2 2>/dev/null || true
            echo "✅ Déploiement terminé"
